# Generated by Django 3.2.16 on 2023-01-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_accountholder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountholder',
            old_name='stocks_visited',
            new_name='stocks_holding',
        ),
        migrations.AddField(
            model_name='accountholder',
            name='num_shares',
            field=models.FloatField(default=0.0),
        ),
    ]
