# Generated by Django 3.2.16 on 2023-01-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20230120_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='num_shares',
            field=models.CharField(max_length=10),
        ),
    ]
