# Generated by Django 3.2.16 on 2023-01-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_accountholder_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumShares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='accountholder',
            name='shares',
        ),
        migrations.AddField(
            model_name='accountholder',
            name='shares',
            field=models.ManyToManyField(to='myapp.NumShares'),
        ),
    ]
