# Generated by Django 3.2.16 on 2023-01-21 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20230121_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountholder',
            name='num_shares',
        ),
    ]
